export const BREAKPOINTS = [
  {
    id: 0,
    title: 'Butterfly',
    subtitle: '',
    image_name: '',
    video: '',
    description:
      'The bunny has just noticed a beautiful butterfly flying above its head',
    time: '76.389439',
    duration: '596.48',
  },
  {
    id: 1,
    title: 'Waking Up',
    subtitle: '',
    image_name: '',
    video: '',
    description: 'The lazy bunny is waking up after a long nap',
    time: '39.65568',
    duration: '596.48',
  },
  {
    id: 2,
    title: 'Hiding',
    subtitle: '',
    image_name: '',
    video: '',
    description:
      'The bunny is scared, trying to run away, and hid behind the tree',
    time: '229.799525',
    duration: '596.48',
  },
  {
    id: 3,
    title: 'Trap',
    subtitle: '',
    image_name: '',
    video: '',
    description: 'The bunny has an idea that he is going to build a trap',
    time: '259.994016',
    duration: '596.48',
  },
  {
    id: 4,
    title: 'Squirrel',
    subtitle: '',
    image_name: '',
    video: '',
    description: 'The evil squirrel is about to attack the bunny',
    time: '395.893346',
    duration: '596.48',
  },
  {
    id: 5,
    title: 'Busted',
    subtitle: '',
    image_name: '',
    video: '',
    description: 'The evil squirrel is finnaly in the hands of the angry bunny',
    time: '457.559238',
    duration: '596.48',
  },
  {
    id: 6,
    title: 'The End',
    subtitle: '',
    image_name: '',
    video: '',
    description: 'The big bunny is using the squirrel as a kite',
    time: '482.029321',
    duration: '596.48',
  },

  {
    id: 7,
    title: 'Payback',
    subtitle: '',
    image_name: '',
    video: '',
    description: 'The evil Squirrel got what he deserved :P',
    time: '593.665175',
    duration: '596.48',
  },
  {
    id: 8,
    title: 'Image Thumbnail',
    subtitle: '',
    image_name: 'image_0.jpeg',
    video: '',
    description: 'This is a custom Image thumbnail',
    time: '570',
    duration: '596.48',
  },
];
